# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://tiffduong.github.io/
baseurl: /sustain/
title: Tiffany Duong
author:  Tiffany Duong
description: Personal blog and resume
avatar: profile.png
email: duongtiffany20@gmail.com
github: tiffduong
linkedin: tiffanydinhduong



# needed for travis-ci build
exclude: [vendor]
